// utils/PDFExport.js

import { Platform } from 'react-native';
import { Share } from 'react-native';

class PDFExport {
    static async generateProfitReportPDF(reportData, inventoryStats) {
        try {
            const today = new Date().toISOString().split('T')[0];

            // Validate report data
            PDFExport.validateReportData(reportData);

            // Create a simple text-based report (in real app, use a proper PDF library)
            const reportContent = this.generateReportContent(reportData, inventoryStats, today);

            // For now, we'll share as text file. In production, use react-native-html-to-pdf
            const shareOptions = {
                title: `Profit Report - ${today}`,
                message: reportContent,
                subject: `Profit Margin Report - ${today}`,
            };

            await Share.open(shareOptions);
            return true;
        } catch (error) {
            console.error('PDF Export error:', error);
            throw new Error('Failed to generate report');
        }
    }

    static generateReportContent(report, inventoryStats, date) {
        const header = `
🏪 TRACK BIZ - PROFIT MARGIN REPORT
📅 Date: ${date}
⏰ Generated: ${new Date().toLocaleString()}
───────────────────────────────────────
    `.trim();

        const summary = `
💰 DAILY SUMMARY:
• Total Sales: Ksh ${report?.totalSales?.toLocaleString() || '0'}
• Cost of Goods: Ksh ${report?.totalCost?.toLocaleString() || '0'}
• Gross Profit: Ksh ${report?.totalProfit?.toLocaleString() || '0'}
• Profit Margin: ${report?.margin || '0'}%
• Transactions: ${report?.transactionCount || '0'}
    `.trim();

        let itemsBreakdown = '';
        if (report?.items && report.items.length > 0) {
            itemsBreakdown = '\n\n📊 ITEMIZED BREAKDOWN:\n';
            itemsBreakdown += 'Item'.padEnd(20) + 'Sold'.padEnd(8) + 'Retail'.padEnd(12) + 'Cost'.padEnd(12) + 'Profit\n';
            itemsBreakdown += '─'.repeat(60) + '\n';

            report.items.forEach(item => {
                itemsBreakdown +=
                    item.name.substring(0, 18).padEnd(20) +
                    String(item.sold).padEnd(8) +
                    `Ksh ${item.retailPrice}`.padEnd(12) +
                    `Ksh ${item.wholesalePrice}`.padEnd(12) +
                    `Ksh ${item.profit.toLocaleString()}\n`;
            });
        }

        let inventorySection = '';
        if (inventoryStats) {
            inventorySection = `
        
📦 INVENTORY INSIGHTS:
• Total Stock Value: Ksh ${inventoryStats.totalStockValue?.toLocaleString() || '0'}
• Total Cost Value: Ksh ${inventoryStats.totalCostValue?.toLocaleString() || '0'}
• Potential Profit: Ksh ${inventoryStats.totalPotentialProfit?.toLocaleString() || '0'}
• Active Items: ${inventoryStats.activeItems || '0'}
      `.trim();

            if (inventoryStats.bestValueItems.length > 0) {
                inventorySection += '\n\n🏆 BEST VALUE ITEMS:';
                inventoryStats.bestValueItems.forEach((item, index) => {
                    inventorySection += `\n${index + 1}. ${item.name} - Ksh ${(item.unitPrice - item.wholesalePrice).toLocaleString()} profit (${item.profitMargin}% margin)`;
                });
            }

            if (inventoryStats.lowMarginItems.length > 0) {
                inventorySection += '\n\n⚠️ LOW MARGIN ALERTS:';
                inventoryStats.lowMarginItems.forEach(item => {
                    inventorySection += `\n• ${item.name} - ${item.profitMargin}% margin`;
                });
            }
        }

        const footer = `
        
───────────────────────────────────────
📱 Generated by Track Biz App
🔒 Secure & Encrypted
    `.trim();

        return header + '\n' + summary + itemsBreakdown + inventorySection + footer;
    }

    static async exportWeeklyReport(weeklyReports) {
        try {
            const today = new Date().toISOString().split('T')[0];

            let reportContent = `
🏪 TRACK BIZ - WEEKLY PROFIT REPORT
📅 Period: ${today} (Last 7 Days)
⏰ Generated: ${new Date().toLocaleString()}
───────────────────────────────────────
      `.trim();

            Object.entries(weeklyReports).forEach(([date, report]) => {
                reportContent += `\n\n📅 ${date}:`;
                reportContent += `\n• Sales: Ksh ${report.totalSales?.toLocaleString() || '0'}`;
                reportContent += `\n• Profit: Ksh ${report.totalProfit?.toLocaleString() || '0'}`;
                reportContent += `\n• Margin: ${report.margin || '0'}%`;
                reportContent += `\n• Transactions: ${report.transactionCount || '0'}`;

                if (report.bestSellingItem) {
                    reportContent += `\n• Best Seller: ${report.bestSellingItem.name} (${report.bestSellingItem.sold} sold)`;
                }
            });

            const shareOptions = {
                title: `Weekly Profit Report - ${today}`,
                message: reportContent,
                subject: `Weekly Profit Margin Report - ${today}`,
            };

            await Share.share(shareOptions);
            return true;
        } catch (error) {
            console.error('Weekly export error:', error);
            throw new Error('Failed to generate weekly report');
        }
    }

    static validateReportData(reportData) {
        if (!reportData) {
            throw new Error('No report data provided');
        }
        if (typeof reportData !== 'object') {
            throw new Error('Invalid report data format');
        }
        // Check for essential fields
        const requiredFields = ['totalSales', 'totalCost', 'totalProfit', 'margin'];
        const missingFields = requiredFields.filter(field => reportData[field] === undefined);
        if (missingFields.length > 0) {
            console.warn('Missing fields in report data:', missingFields);
        }
        return true;
    }
}

export default PDFExport;